config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :employees, :controllers => {registrations: 'registrations'}

  root to: "clients#index"

  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar#new_event', as: 'new_event', calendar_id: /[^\/]+/


  resources :employees do
    resources :services
  end

  resources :clients do
    resources :services
  end

  resources :clients do
    resources :invoices
  end
  
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :client
  belongs_to :employee

  validates :description, :date, :time, :client_id, :employee_id, :presence => true


  def cost
    rate = self.client.rate
    time = self.time.to_f
    bill = (time/60).to_f * rate
    return bill.to_i
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_employee!

  def index
    @client = Client.find(params[:client_id])
    @services = @client.services.all
  end

  def show
    @client = Client.find(params[:client_id])
    @service = Service.find(params[:id])
  end

  def new
    @client = Client.find(params[:client_id])
    @service = Service.new
  end

  def create
    @client = Client.find(params[:client_id])
    @service = Service.new(service_params)
    if @service.save
      redirect_to client_service_path(@client, @service)
    else
      render :new
    end
  end

  def edit
    @client = Client.find(params[:client_id])
    @service = Service.find(params[:id])
  end

  def update
    @client = Client.find(params[:client_id])
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to client_path(@client)
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:client_id])
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to client_path(@client)
  end

  private
  def service_params
    params.require(:service).permit(:description, :date, :time, :client_id, :employee_id, :paid)
  end
end

app/views/services/_form.html.erb
<%= render 'layouts/errors', :object => @service %>

<%= form_for [@client,@service] do |f| %>
  <div class="card">
   <%= f.hidden_field :client_id, :value => @client.id %>
   <%= f.hidden_field :employee_id, :value => current_employee.id %>

   <%= f.label :description %>
   <%= f.text_field :description %>

   <%= f.label :date %>
   <%= f.date_field :date %>

   <%= f.label "Time (in minutes)" %>
   <%= f.number_field :time %>


   <%= f.submit class: "btn link-btn black" %>
  </div>
 <% end %>

<div class="card">
  <h2><time>00:00:00</time></h2>
  <button class="btn black" id="start">start</button>
  <button class="btn black" id="stop">stop</button>
  <button class="btn black" id="clear">clear</button>
</div>

app/views/services/_pay.html.erb
<%= render 'layouts/errors', :object => @service %>

<%= form_for [@client, @service] do |f| %>

   <%= f.hidden_field :paid, :value => true %>

   <%= f.submit "Paid", class: "btn link-btn black" %>

 <% end %>

app/views/services/edit.html.erb
<h3>Edit</h3>
<%= form_for [@client, @service] do |f| %>
  <div class="card">
   <%= f.hidden_field :client_id, :value => @client.id %>
   <%= f.hidden_field :employee_id, :value => current_employee.id %>

   <%= f.label :description %>
   <%= f.text_field :description %>

   <%= f.label :date %>
   <%= f.date_field :date %>

   <%= f.label "Time (in minutes)" %>
   <%= f.number_field :time %>

   <%= f.submit class: "btn link-btn black" %>
  </div>
 <% end %>

app/views/services/index.html.erb
<h1>Services</h1>

<% @services.each do |service| %>
  <p>
    <%= service.description %>
  </p>
<% end %>

app/views/services/new.html.erb
<%= render('form') %>

app/views/services/show.html.erb
<h1>Service</h1>
<div class="card">

  <p><strong>Date:</strong> <%= @service.date.strftime('%D') %></p>
  <p><strong>Description:</strong> <%= @service.description %></p>
  <p><strong>Time:</strong> <%= @service.time %> minutes</p>
  <p><strong>Balance:</strong> $<%= @service.cost %></p>
  <p><strong>Paid:</strong> <%= @service.paid %></p>
  <p><strong>Employee:</strong> <%= @service.employee.name %></p>

  <%= render('pay') %>

  <p><%= link_to "Edit", edit_client_service_path(@client,@service) %> | <%= link_to "Delete", client_service_path(@client,@service), method: :delete, data: {confirm: 'Delete Service?'} %></p>
  <%= link_to "All Services", client_path(@client) %>
</div>