config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :employees, :controllers => {registrations: 'registrations'}

  root to: "clients#index"

  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar#new_event', as: 'new_event', calendar_id: /[^\/]+/


  resources :employees do
    resources :services
  end

  resources :clients do
    resources :services
  end

  resources :clients do
    resources :invoices
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :services
  has_many :employees, :through => :services

  validates :name, :address, :contact_name, :contact_email, :contact_number, :rate, :presence => true

  def total
    time = 0
    self.services.each do |service|
      time = time + service.time
    end
    return time
  end

  def bill
    rate = self.rate
    time = 0
    self.services.each do |service|
      if !service.paid?
        time = time + service.time
      end
    end
    bill = (time.to_f/60.to_f) * rate
    return bill.to_i
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_employee!

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @total = @client.total
    @billable = @client.bill
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to client_path(@client)
    else
      render :new
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end


private
def client_params
  params.require(:client).permit(:name, :address, :contact_name, :contact_email, :contact_number, :rate)
end

end

app/views/clients/_detail.html.erb
<p><strong>Contact Name:</strong> <%= @client.contact_name %> </p>
<p><strong>Contact Email:</strong> <%= @client.contact_email %> </p>
<p><strong>Contact Number:</strong> <%= @client.contact_number %> </p>
<p><strong>Hourly Rate:</strong> <%= @client.rate %> </p>

app/views/clients/_form.html.erb
<%= render 'layouts/errors', :object => @client %>

<%= form_for [@employee,@client] do |f| %>
  <div class="card">
  <div class="input-field">
    <%= f.text_field :name, type: 'text', class: 'validate' %>
    <%= f.label :name %>
  </div>

  <div class="input-field">
    <%= f.text_field :address, type: 'text', class: 'validate' %>
    <%= f.label :address %>
  </div>

  <div class="input-field">
    <%= f.text_field :contact_name, type: 'text', class: 'validate' %>
    <%= f.label :contact_name %>
  </div>

  <div class="input-field">
    <%= f.text_field :contact_email, type: 'text', class: 'validate' %>
    <%= f.label :contact_email%>
  </div>

 <div class="input-field">
  <%= f.text_field :contact_number, type: 'text', class: 'validate' %>
  <%= f.label :contact_number%>
 </div>

 <div class="input-field">
   <%= f.text_field :rate, type: 'text', class: 'validate' %>
   <%= f.label :rate%>
 </div>
   <br>
   <br>
   <%= f.submit class: "btn link-btn black" %>
  </div>
 <% end %>

app/views/clients/index.html.erb
<% if !@clients.empty? %>
  <div class="collection white">
    <% @clients.each do |client| %>
      <h5 class=collection-item> <%= link_to client.name, client_path(client) %>    <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe, client_path(client), class: "right", method: :delete, data: {confirm: "Delete?"} %></h5>
    <% end %>
  </div>
<% else %>
  <h4>Click below to start adding clients!</h4>
  <%= link_to "Add Client", new_client_path() %>
<% end %>

app/views/clients/new.html.erb
<%= render 'form' %>

app/views/clients/show.html.erb
<div class="card">
  <h3><%= @client.name %></h3>
  <h5 class="right">Balance Due: $<%= @billable %> </h5>
  <h5><%= @client.address %></h5>
  <div id="client-detail"></div>
  <%= link_to "...", client_path(@client), id: 'detail-button', remote: true %>
</div>



<div class="collection white">
  <span class="right"><%= link_to "Add Service", new_client_service_path(@client) %></span><br>
  <span class="right"><%= link_to "Create Invoice", client_invoices_path(@client) %></span>
  <h3 class="center">Services</h3>
  <% @client.services.order(:date).each do |service| %>
    <% if !service.paid? %>
      <h5 class="collection-item"> <%= service.date.strftime('%D') %> <%= link_to service.description, client_service_path(@client, service) %> <span class='right'>$<%= service.cost %></span> </h5>
    <% end %>
  <% end %>
</div>

<% @client.services.order(:date).each do |service| %>
  <% if service.paid? %>
  <div class="collection white">
    <h5 class="collection-item"> <%= service.date.strftime('%D') %> <%= link_to service.description, client_service_path(@client, service) %><span class='right'>Paid</span></h5>
  </div>
  <% end %>
<% end %>

app/views/clients/show.js.erb
$('#detail-button').hide();
$('#client-detail').html("<%= j render('detail') %>");