config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :employees, :controllers => {registrations: 'registrations'}

  root to: "clients#index"

  get '/redirect', to: 'calendar#redirect', as: 'redirect'
  get '/callback', to: 'calendar#callback', as: 'callback'
  get '/calendars', to: 'calendar#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'calendar#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'calendar#new_event', as: 'new_event', calendar_id: /[^\/]+/


  resources :employees do
    resources :services
  end

  resources :clients do
    resources :services
  end

  resources :clients do
    resources :invoices
  end
  
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>You made a goof.</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickTrack</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper black">
        <a href="/" class="brand-logo">QuickTrack</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">

          <% if employee_signed_in? %>
            <li><%= link_to "Clients", clients_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Add Client", new_client_path, :class => 'navbar-link'  %></li>
            <strong><li><%= current_employee.name %></li></strong>
            <li><%= link_to "Logout", destroy_employee_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
             <li><%= link_to "Sign up", new_employee_registration_path, :class => 'navbar-link'  %></li>
             <li><%= link_to "Login", new_employee_session_path, :class => 'navbar-link' %></li>
           <% end %>

        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>